appointments/urls.py
from django.urls import path
from appointments import views
from appointments.views import ManageAppointments, AppointmentView, AppointmentHistory


urlpatterns = [
    path('manage-appointments', ManageAppointments.as_view(), name='manage_appointments'),
    path('appointment', views.AppointmentView, name='appointment'),
    path('appointment-history', views.AppointmentHistory, name='appointment-history'),
]

violet/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from GHB import views
from GHB.views import SignUpView, ActivateView, CheckEmailView, SuccessView
from django.contrib.auth import views as auth_views

app_name = 'GHB'


urlpatterns = [
    path('GHB/', admin.site.urls),
    path('', include('HairStyles.urls')),
    path('', include('appointments.urls')),
    path('', views.home_view, name='index'),
    path('accounts/login/', auth_views.LoginView.as_view()),
    path('about_us/', views.about_us_view, name='about_us'),
    path('contacts/', views.contacts_view, name='contacts'),
    path('profile/', views.profile_view, name='profile'),
    path('update-profile/', views.update_profile, name='update-profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('activate/<uidb64>/<token>/', ActivateView.as_view(), name='activate'),
    path('check-email/', CheckEmailView.as_view(), name='check_email'),
    path('success/', SuccessView.as_view(), name='success'),
    path('', include('django.contrib.auth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),	
]



urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

appointments/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.



class Appointment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    booked_item = models.CharField(max_length=1000)
    phone_number = models.CharField(max_length=15)  
    address = models.CharField(max_length=200)  
    applied_on = models.DateTimeField(auto_now_add=True)
    date_scheduled = models.DateField(auto_now_add=False, null=True, blank=True)
    
    
    def __str__(self):
        return (self.name)

appointments/forms.py
from django import forms
from .models import *

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['name', 'user', 'booked_item', 'phone_number', 'address']



        

appointments/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from HairStyles.models import HairType
from .models import Appointment
from .forms import AppointmentForm
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.contrib import messages
from django.template import context


# Create your views here.


@login_required
def AppointmentView(request):
    form = AppointmentForm(request.POST or request.GET)
    hair_types = HairType.objects.all()
    user = request.user
    if request.POST:
        form = AppointmentForm(request.POST)
        if form.is_valid():      
            name = form.cleaned_data['name']
            phone_number = form.cleaned_data['phone_number']
            booked_item = form.cleaned_data['booked_item']
            html = render_to_string('email_html_strings/booked-notification.html', {
                'name': name,
                'phone_number': phone_number,
                'booked_item': booked_item
            })

            send_mail('Appointment Application', html_message=html)
            form.save()
            messages.success(request, f'Hi {user.first_name}, thanks for booking an appointment, a date will be scheduled for your appointment and sent via Mail from the Goodness Hair Braid team. ')
            return redirect('appointment-history')
    return render(request, 'appointment_form.html', {'form': form, 'hair_types': hair_types})


@login_required
def AppointmentHistory(request):
    user = request.user
    appointments = Appointment.objects.filter(user=user).order_by('applied_on')
    return render(request, 'appointment_history.html', {'appointments': appointments})



class ManageAppointments(ListView):
    model = Appointment
    template_name = 'manage_appointments.html'
    context_object_name = 'appointments'
    login_required = True
    #paginate_by = 6

    def post(self, request):
        date = request.POST.get('date')
        appointment_id = request.POST.get('appointment-id')
        appointment = Appointment.objects.get(id=appointment_id)
        appointment.date_scheduled = date
        name = appointment.name
        item = appointment.booked_item
        appointment.save()

        html = render_to_string('appointments-email.html', {
                'name': name,
                'date': date,
                'item': item
                
            })

        send_mail('Your Appointment has been Accepted and Scheduled', html_message=html)
        messages.success(request, f'Date scheduled successfully for {appointment.name}')
        return HttpResponseRedirect(request.path)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        appointments = Appointment.objects.all().order_by('-applied_on')
        context.update({
            'appointments': appointments,
            'title':'Manage-Appointments'
        })
        return context

templates/about_us.html
<!DOCTYPE html>
<head>
    {% extends 'base.html' %}

    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'css/about_us.css' %}">

</head>


{% block content %}
<body>
    <div class="container">
        <div class="row">
            <h3 style="color: teal; display: 
            flex; justify-content: center; margin-top: 50px;">
                <strong style="color: #333;">ABOUT US</strong> 
            </h3>
        </div><br><br>
        <div class="row">
            <h5 style="color: teal; display: flex; justify-content: center">
                GOODNESS HAIR BRAIDS
            </h5><hr class="slant-line">
            <p style="color: #666;">GHB is an Exceptional Beauty Salon located in Houston, Texas. Our mission is to provide the highest quality service
              , in union with the highest quality products for the well-being of our guests and the environment.
            </p>
        </div>
        <div class="row" style="margin-top: 20px;">
          <h6 style="display: flex; justify-content: center;">WHY WE EXIST</h6>
            <p style="display: flex; justify-content: center; color: #666">At GHB, our main focus is on the unique needs and desires of our guests, making us the most unique
            salon in Houston: we have professional stylists that are ready to provide professional service,
            experience and results above and beyond expectations.</p>
          </p><hr>
        </div>
    </div>
</body><br><br><br>


<!-- Footer -->
<footer class="bg-dark text-center text-white" style="margin-top: 100px;">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      
       <!-- Instagram -->
       <a class="btn btn-outline-light btn-floating m-1" target="_blank" href="https://www.instagram.com/goodnesshairbraids/" role="button">
        <i class="fab fa-instagram"></i>
      </a>
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-facebook-f"></i>
      </a>

    </section>
    <!-- Section: Social media -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a style="text-decoration: none;" href="/" class="text-white" >Home</a>
            </li>
            <li>
              <a style="text-decoration: none;" href="/about_us" class="text-white">About us</a>
            </li>
            <li>
              <a style="text-decoration: none;" href="/service" class="text-white">Service</a>
            </li>
            <li>
              <a style="text-decoration: none;" href="/contacts" class="text-white">Contact us</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Services</h5>

          <ul class="list-unstyled mb-0">
            <li>Braids</li>
            <li>Twist</li>
            <li>Crochet</li>
            <li>Fox Locs</li>
            <li>Kids style</li>
            <li>Natural Hair</li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Book Appointments</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a style="text-decoration: none;" class="text-white" href="/appointment">Book Appointment</a>
            </li>
            <li>
              <a style="text-decoration: none;" class="text-white" href="/appointment-history">Appointment History</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Open hours</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <p>Monday-saturday: 9am To 5pm</p>
            </li>
            <li>
              <p style="color: #f59;">Sundays: closed</p>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © {% now "Y" %} Copyright:
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

       <script src="{% static 'jquery.min.js' %}"></script>
       <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

{% endblock content %}

templates/activate_account.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body style="background-color: grey;">
    <div class="container-fluid" style="background-color: teal; padding-top: 15px; padding-bottom: 15px">
        <center>
            <h1 style="color: #fff; ">GOODNESS HAIR BRAID</h1>
        </center>
    </div>

    <div class="container-fluid" style="background-color: #000; color: #fff; padding-top: 20px; padding-bottom: 150px">
        <b style="margin-left: 10px;">Hello {{ user.first_name|upper }}!</b><br>

        <p style="margin-left: 10px;">We noticed you just sign up on our website.</p>
        <p style="margin-left: 10px;">
            Please confirm your email address to activate your account  
        </p>
        <center style="margin-top: 30px;">
            <button style="background-color: teal;">
                <a href="" style="text-decoration: none; color: white; font-size: 22px">
                    Confirm email address
                </a>
            </button>
        </center>
    </div>
    
</body>

<footer style="background-color: teal; padding-bottom: 300px; padding-top: 50px">

    <center>
        <img style="height: 60px; width: 60px; margin-bottom: 30px"  src="{% static 'media/ghb.png' %}" alt="GHB logo">
    </center>
    <center>
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
            <i class="fab fa-instagram"></i>
        </a>
    </center>
   
</footer>


</html>

templates/activate_account_invalid.html
<!DOCTYPE html>
<html lang="en">

{% extends 'base.html' %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

{% block content %}
<body>
    <p>Invalid activation link</p> 
</body>
{% endblock content %}
</html>

templates/appointment_form.html
<!DOCTYPE html>

{% extends 'base.html' %}

{% load static %}

{% load crispy_forms_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
  
    <title>Book service</title>
</head>

{% block content %}

<body>
  <form method="post">

    <div>
        <center><h5>Fill the form to book</h5></center><br><br>
        
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">            
                <div class="col-md-6">
                    <div class="col-md-12">
                      <h6 style="color: #444;">OPEN HOURS: &nbsp; Monday-Saturday &nbsp; 9am-5pm<h6 style="color: #f06;">Sunday(closed)</h6></h6><br>
                      
                        <form class="form-inline" action="" method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <p>
                                  <label for="id_name"><h6>Name:</h6></label>
                                  <input class="form-control" type="text" name="name" value="{{ user.first_name|upper }} {{ user.last_name|upper }}" maxlength="100" required="" id="id_name" readonly>
                                </p>

                                <p>
                                  <input class="form-control" type="hidden" name="user" value="{{ user.id }}" maxlength="100" required="" id="id_user" readonly>
                                </p>

                                <p>
                                    <label for="id_booked_item"><h6>Select Hair Type:</h6></label>
                                    <select class="form-control" class="custom-select my-1 mr-sm-2" name="booked_item" required="" id="id_booked_item">
                                      <option selected>Select</option>
                                      {% for type in hair_types %}
                                        <option>{{ type.subCategory }} &nbsp; &nbsp; &nbsp; ${{ type.price }}</option>
                                      {% endfor %}
                                    </select>
                                </p>
                                <p>
                                    <label for="id_phone_number"><h6>Phone number:</h6></label>
                                    <input class="form-control" type="text" name="phone_number" maxlength="15" required="" id="id_phone_number">
                                </p>
                                <p>
                                    <label for="id_address"><h6>Your location:</h6></label>
                                    <input class="form-control" type="text" name="address" placeholder="US, Houston residents only." maxlength="200" required="" id="id_address">
                                </p><br>

                                <div class="d-grid">
                                    <button class="btn btn-lg btn-book" style="color: #fff; background-color: teal" type="submit">SUBMIT</button>
                                </div>
                            
                            </div>                   
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>


 
<!-- Footer -->
<footer class="bg-dark text-center text-white" style="margin-top: 100px;">
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      
       <!-- Instagram -->
       <a class="btn btn-outline-light btn-floating m-1" target="_blank" href="https://www.instagram.com/goodnesshairbraids/" role="button">
        <i class="fab fa-instagram"></i>
      </a>
      <!-- Facebook -->
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
        <i class="fab fa-facebook-f"></i>
      </a>

    </section>
    <!-- Section: Social media -->

    <!-- Section: Links -->
    <section class="">
      <!--Grid row-->
      <div class="row">
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Links</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a style="text-decoration: none;" href="/" class="text-white" >Home</a>
            </li>
            <li>
              <a style="text-decoration: none;" href="/about_us" class="text-white">About us</a>
            </li>
            <li>
              <a style="text-decoration: none;" href="/service" class="text-white">Service</a>
            </li>
            <li>
              <a style="text-decoration: none;" href="/contacts" class="text-white">Contact us</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Services</h5>

          <ul class="list-unstyled mb-0">
            <li>Braids</li>
            <li>Twist</li>
            <li>Crochet</li>
            <li>Fox Locs</li>
            <li>Kids style</li>
            <li>Natural Hair</li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Book Appointments</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <a style="text-decoration: none;" class="text-white" href="/appointment">Book Appointment</a>
            </li>
            <li>
              <a style="text-decoration: none;" class="text-white" href="/appointment-history">Appointment History</a>
            </li>
          </ul>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
          <h5 class="text-uppercase">Open hours</h5>

          <ul class="list-unstyled mb-0">
            <li>
              <p>Monday-saturday: 9am To 5pm</p>
            </li>
            <li>
              <p style="color: #f59;">Sundays: closed</p>
            </li>
          </ul>
        </div>
        <!--Grid column-->
      </div>
      <!--Grid row-->
    </section>
    <!-- Section: Links -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © {% now "Y" %} Copyright:
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>

    
</body>
</html>
{% endblock content %}





  

templates/appointment_history.html
{% extends 'base.html' %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>

</head>

{%  block content %}
   
    {% for message in messages %}
    <div class="container-fluid">
        <p style="color: green;"><i class="fa fa-check"></i>&nbsp; {{ message }}</p>
    </div>
    
    {% endfor %}

    <body >
      {% if appointments %}
        <div style="margin-top: 50px;" class="container">
            <div class="table-responsive">
                <table class="table table-borderless">
                    
                    <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col">ITEM</th>
                            <th scope="col">ADDRESS</th>
                            <th scope="col">DATE SCHEDULE</th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    {% for app in appointments %}
                    <div class="container-fluid">
                        <tbody>
                            <tr>
                                <td></td>
                                <td></td>
                                <td></td>
                                <td><p style="color: #666;" >{{ app.booked_item }}<p></td>
                                <td><p style="color: #666;" >{{ app.address }}</p></td>
                                <td><p style="color: #666;" >{{ app.date_scheduled }}</p></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                        </tbody>
                    </div>
                    
                    {% endfor %} 
                </table>
            </div>  
        {% else %}
        <h6 style="margin-top: 100px; color: #666;" class="text-center">You have no booked record</h6>
        {% endif %}
        </div>
    </body>

{%  endblock content %}
</html>

templates/appointments-email.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<p></p>
<p></p>
<body>
    <div class="container-fluid" style="background-color: teal; padding-top: 15px; padding-bottom: 15px">
        <center>
            <h1 style="color: #fff; ">GOODNESS HAIR BRAID</h1>
        </center>
    </div>

    <div class="container-fluid" style="background-color: #000; color: #fff; padding-top: 20px; padding-bottom: 150px">
        <b style="margin-left: 10px;">Hello  {{name}}</b><br>

        <p style="margin-left: 10px;">Your appointment has been accepted</p>
        <p style="margin-left: 10px;">
            Date schedule is <b>{{date}}</b>
        </p>
        <p style="margin-left: 10px;">what you booked: {{item}}</p>
        <p style="margin-left: 10px;">Thanks for your application. If you want a date re-schedule you can always reach us through one of the contact means by specifying the date you wish.</p>
        <center style="margin-top: 50px;">
            <button style="background-color: teal;">
                <a style="text-decoration: none; color: white; font-size: 22px" href="/contacts">contact us</a>   
            </button>
                
        </center>
    </div>

</body>
    
<footer style="background-color: teal; padding-bottom: 300px; padding-top: 50px">

    <center>
        <img style="height: 60px; width: 60px; margin-bottom: 30px"  src="{% static 'media/ghb.png' %}" alt="GHB logo">
    </center>
    <center>
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
            <i class="fab fa-facebook-f"></i>
        </a>
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
            <i class="fab fa-instagram"></i>
        </a>
    </center>
    
</footer>

</html>

templates/check_email.html
<!DOCTYPE html>
<html lang="en">

{% extends 'base.html' %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

{% block content %}

<body>
    <div class="mx-auto text-center">
        <h4>Activate your account</h4>
        <p>Please check your inbox and verify your email address</p>
    </div>
</body>
</html>

{% endblock content %}

templates/password_reset.html
<!DOCTYPE html>

{% load crispy_forms_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>password_reset</title>
</head>
<body>
    <a href="/login">previous page</a>
    <h5>Reset your password below</h5>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}<br>
        <button type="submit">Reset password</button>
    </form>
</body>
</html>

templates/profile.html
{% extends 'base.html' %}

{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Profile</title>
</head>
<body>
  
{% block content %}
  <section class="vh-100" style="background-color: #eee;">
      <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-lg-12 col-xl-11">
            <div class="card text-black" style="border-radius: 25px;">
              <div class="card-body p-md-5">
                <div class="row justify-content-center">
                  <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
                    {% for message in messages %}
                    <div style="background-color: #333; border-radius: 15px" class="container-fluid">
                      <p style="color: #fff;"><i class="fa fa-check"></i>&nbsp; {{ message }}</p>
                    </div>
                      
                    {% endfor %}

                    <h1 style="color: #333;">{{ x|upper }}{{ y|upper }}</h1><hr>
                    
                    <p style="color: grey;"><strong style="color: grey;">Username</strong>&nbsp; {{ user.username }}</p>
                    <p style="color: grey;"><strong style="color: grey;">Firstname</strong>&nbsp; {{ user.first_name}}</p>
                    <p style="color: grey;"><strong style="color: grey;">Lastname</strong>&nbsp; {{ user.last_name }}</p>
                    <p style="color: grey;"><strong style="color: grey;">Email</strong>&nbsp; {{ user.email}}</p><hr>
                    <button style="background-color: teal;" class="btn btn-sm"><a style="text-decoration: none; color: #333" href="/update-profile">Update Profile</a></button>        
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock content %} 

</body>
</html>

templates/successful.html
<!DOCTYPE html>
<html lang="en">

{% extends 'base.html' %}

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

{% block content %}

<body>
    <div class="mx-auto text-center">
        <h5>Congrats! you just verified your account</h5>
    </div>
</body>

{% endblock content %}

</html>